TestCaseTrackingSystem/TestCaseTrackingSystem/Models/Chart/ChartModel.cs
namespace TestCaseStorage.Models.Chart
{
    public class ChartModel
    {
        public string YLabel { get; set; }
        public string Guid { get; set; }
        public ChartType Type { get; set; }
        public string Labels { get; set; }
        public string Values { get; set; }
        public string ChartColor { get; set; }
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Models/Chart/ChartType.cs
namespace TestCaseStorage.Models.Chart
{
    public enum ChartType
    {
        Bar
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Models/Shared/EditDeleteSectionModel.cs
namespace TestCaseStorage.Models.Shared
{
    public class EditDeleteSectionModel
    {
        public EditDeleteSectionModel(string controller, string deleteItemName, object hiddenIdentifier, string editAction = "Edit", string deleteAction = "Delete")
        {
            Controller = controller;
            DeleteItemName = deleteItemName;
            HiddenIdentifier = hiddenIdentifier;
            EditAction = editAction;
            DeleteAction = deleteAction;
        }

        public string DeleteItemName { get; set; }
        public string Controller { get; set; }
        public string EditAction { get; set; }
        public string DeleteAction { get; set; }
        public object HiddenIdentifier { get; set; }
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Models/Shared/EditLineModel.cs
namespace TestCaseStorage.Models.Shared
{
    public enum ControlType
    {
        TextBox,
        Date
    }

    public class EditLineModel
    {
        public EditLineModel(string controlName, string controlValue, ControlType controlType, string placeHolder)
        {
            ControlType = controlType;
            PlaceHolder = placeHolder;
            ControlValue = controlValue;
            ControlName = controlName;
        }

        public string PlaceHolder { get; }
        public ControlType ControlType { get; }
        public string ControlName { get; }
        public string ControlValue { get; }
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Controllers/BacklogController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using DataAccess;
using DataAccess.Repositories.Implementation;
using Services.DTO;
using Services.Implementation;
using Services.Interfaces;
using TestCaseStorage.Infrastructure.Extensions;
using TestCaseStorage.Models.BacklogItems;

namespace TestCaseStorage.Controllers
{
    [Authorize]
    public class BacklogController : Controller
    {
        private readonly IBacklogService BackogService;
        private readonly IUserService UserService;
        
        public BacklogController()
        {
            BackogService = new BacklogDbService(new TCTSUnitOfWork(new TCTSDataContext()));
            UserService = new UserDbService(new TCTSUnitOfWork(new TCTSDataContext()));
        }

        [HttpGet]
        public ViewResult List()
        {
            var listModel = Mapper.Map<IEnumerable<BacklogItemViewModel>>(BackogService.GetAllBacklogItems());
            
            return View("List", listModel);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var editModel = Mapper.Map<BacklogItemEditModel>(new BacklogItemDto());
            editModel.Users = UserService.GetAllUsers().ToSelectList(t => t.Login, t => t.ID);
            editModel.UserCreatedId = (int)Membership.GetUser(User.Identity.Name).ProviderUserKey;

            return View("Add", editModel);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var currentBacklogItemModel = Mapper.Map<BacklogItemEditModel>(BackogService.GetBacklogItemById(id));
            currentBacklogItemModel.Users = UserService.GetAllUsers().ToSelectList(t => t.Login, t => t.ID, t => t.Login == currentBacklogItemModel.AssignedTo);

            return View("Edit", currentBacklogItemModel);
        }

        [HttpPost]
        public RedirectToRouteResult Delete(int id)
        {
            BackogService.DeleteBacklogItem(id);

            return RedirectToAction("List");
        }

        [HttpPost]
        public RedirectToRouteResult Update(BacklogItemEditModel backlogItem)
        {
            BackogService.Update(Mapper.Map<BacklogItemDto>(backlogItem));

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult AddNew(BacklogItemEditModel backlogItem)
        {
            BackogService.AddNew(Mapper.Map<BacklogItemDto>(backlogItem));

            return RedirectToAction("List");
        }
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Controllers/ChartController.cs
using System.Web.Mvc;
using TestCaseStorage.Models.Chart;
using Services.Implementation;
using DataAccess.Repositories.Implementation;
using DataAccess;
using Services.Interfaces;
using System.Linq;
using DataAccess.Entities;
using Services.DTO;
using System;

namespace TestCaseStorage.Controllers
{
    [Authorize]
    public class ChartController : Controller
    {
        private ITestCaseService TestCaseService { get; }

        public ChartController()
        {
            TestCaseService = new TestCaseService(new TCTSUnitOfWork(new TCTSDataContext()));
        }

        [HttpGet]
        public ActionResult TestersStatisticsChart(TestCaseStatus status = TestCaseStatus.InProgress)
        {
            var chartModel = new ChartModel
            {
                YLabel = GetStatusYLabel(status),
                Guid = "chart",
                Type = ChartType.Bar,
                Labels = string.Join(",", TestCaseService.GetTestersStatistics().Select(t => string.Format("'{0}'", t.TesterName))),
                Values = string.Join(",", TestCaseService.GetTestersStatistics().Select(t => GetStatusValue(status, t))),
                ChartColor = GetStatusColor(status)
            };

            return PartialView("_chart", chartModel);
        }

        private static string GetStatusValue(TestCaseStatus status, TestersStatisticsDto test)
        {
            switch (status)
            {
                case TestCaseStatus.Failed:
                    return test.TestsFailed.ToString();
                case TestCaseStatus.InProgress:
                    return test.TestsInProgress.ToString();
                case TestCaseStatus.Pased:
                    return test.TestsPassed.ToString();
                default:
                    return test.TestsNotStarted.ToString();
            }
        }

        private static string GetStatusYLabel(TestCaseStatus status)
        {
            switch (status)
            {
                case TestCaseStatus.Failed:
                    return "Тестов провалено";
                case TestCaseStatus.InProgress:
                    return "Тестов в процессе";
                case TestCaseStatus.Pased:
                    return "Тестов пройдено";
                default:
                    return "Тестов не начато";
            }
        }

        private static string GetStatusColor(TestCaseStatus status)
        {
            switch (status)
            {
                case TestCaseStatus.Failed:
                    return ConsoleColor.Red.ToString();
                case TestCaseStatus.InProgress:
                    return ConsoleColor.Yellow.ToString();
                case TestCaseStatus.Pased:
                    return ConsoleColor.Green.ToString();
                default:
                    return ConsoleColor.White.ToString();
            }
        }
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Controllers/LoginController.cs
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using DataAccess;
using DataAccess.Repositories.Implementation;
using Services.DTO;
using Services.Exceptions;
using Services.Implementation;
using Services.Interfaces;
using TestCaseStorage.Models.Login;

namespace TestCaseStorage.Controllers
{
    [Authorize]
    public class LoginController : Controller
    {
        private IUserService UserService { get; }

        public LoginController()
        {
            UserService = new UserDbService(new TCTSUnitOfWork(new TCTSDataContext()));
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Login()
        {
            return View("Index");
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginModel loginModel)
        {
            if (ModelState.IsValid && Membership.ValidateUser(loginModel.Login, loginModel.Password))
            {
                FormsAuthentication.SetAuthCookie(loginModel.Login, true);

                UserService.UpdateLastLoginDate(loginModel.Login);

                return RedirectToAction("Index", "Home");
            }

            return View("Index");
        }

        [HttpGet]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult Register(string[] errorMessages = null)
        {
            return View("Register", new RegisterViewModel {ErrorMessages = errorMessages});
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Register(RegisterViewModel user)
        {
            try
            {
                UserService.AddNew(Mapper.Map<UserDto>(user));

                return Login(new LoginModel {Login = user.Login, Password = user.Password});
            }
            catch (DuplicateUserException exception)
            {
                return Register(new []{exception.Message});
            }
        }
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Controllers/NavigationMenuController.cs
using System.Web.Mvc;

namespace TestCaseStorage.Controllers
{
    [Authorize]
    public class NavigationMenuController : Controller
    {
        public ViewResult Show()
        {
            return View("_navigationMenu");
        }
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Controllers/TestCaseController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;
using AutoMapper;
using DataAccess;
using DataAccess.Entities;
using DataAccess.Repositories.Implementation;
using Services.DTO;
using Services.Implementation;
using Services.Interfaces;
using TestCaseStorage.Infrastructure.Extensions;
using TestCaseStorage.Models.TestCases;

namespace TestCaseStorage.Controllers
{
    [Authorize]
    public class TestCaseController : Controller
    {
        private readonly ITestCaseService TestCaseService;
        private readonly IBacklogService BacklogService;
        private readonly IUserService UserService;

        public TestCaseController()
        {
            var unitOfWork = new TCTSUnitOfWork(new TCTSDataContext());

            TestCaseService = new TestCaseService(unitOfWork);
            BacklogService = new BacklogDbService(unitOfWork);
            UserService = new UserDbService(unitOfWork);
        }

        [HttpGet]
        public ViewResult List()
        {
            ViewBag.DisableAdd = !BacklogService.HasAny() || !User.IsInRole(UserRole.QA.ToString());
            ViewBag.IsNotQA = !User.IsInRole(UserRole.QA.ToString());
            var testCasesListModel = Mapper.Map<IEnumerable<TestCaseListViewModel>>(TestCaseService.GetAllTestCases());

            return View("List", testCasesListModel);
        }

        [HttpGet]
        public ViewResult Add()
        {
            var viewModel = new TestCaseAddViewModel
            {
                BacklogItems = BacklogService.GetAllBacklogItems().ToSelectList(t => t.Title, t => t.ID),
                Users = UserService.GetAllTesters().ToSelectList(t => t.Login, t => t.ID)
            };

            return View("Add", viewModel);
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            var testCaseViewModel = Mapper.Map<TestCaseEditViewModel>(TestCaseService.GetTestCaseById(id));
            testCaseViewModel.BacklogItems = BacklogService.GetAllBacklogItems().ToSelectList(t => t.Title, t => t.ID);
            testCaseViewModel.Users = UserService.GetAllTesters().ToSelectList(t => t.Login, t => t.ID);

            return View("Edit", testCaseViewModel);
        }

        [HttpPost]
        public RedirectToRouteResult AddNew(TestCaseAddViewModel testCase)
        {
            var testCaseDto = Mapper.Map<TestCaseDto>(testCase);
            testCaseDto.CreatedByID = (int) Membership.GetUser(User.Identity.Name).ProviderUserKey;
            TestCaseService.AddNew(testCaseDto);

            return RedirectToAction("List");
        }

        [HttpPost]
        public RedirectToRouteResult Update(TestCaseEditViewModel testCase)
        {
            var testCaseDto = Mapper.Map<TestCaseDto>(testCase);
            TestCaseService.Update(testCaseDto);

            return RedirectToAction("List");
        }

        [HttpPost]
        public RedirectToRouteResult Delete(int id)
        {
            TestCaseService.DeleteTestCase(id);

            return RedirectToAction("List");
        }
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Controllers/UserController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using DataAccess;
using DataAccess.Entities;
using DataAccess.Repositories.Implementation;
using Services.DTO;
using Services.Exceptions;
using Services.Implementation;
using Services.Interfaces;
using TestCaseStorage.Models.Users;

namespace TestCaseStorage.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private IUserService UserService { get; }

        public UserController()
        {
            UserService = new UserDbService(new TCTSUnitOfWork(new TCTSDataContext()));
        }

        [HttpGet]
        public ViewResult List()
        {
            ViewBag.DisableAdd = !User.IsInRole(UserRole.Admin.ToString());
            var usersListModel = Mapper.Map<IEnumerable<UserViewModel>>(UserService.GetAllUsers());

            return View("List", usersListModel);
        }

        [HttpGet]
        public ViewResult Add(string[] errorMessages = null)
        {
            return View("Add", new UserViewModel {ErrorMessages = errorMessages});
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            var userModel = Mapper.Map<UserViewModel>(UserService.GetUserById(id));

            return View("Edit", userModel);
        }

        [HttpPost]
        public RedirectToRouteResult Update(UserViewModel user)
        {
            UserService.Update(Mapper.Map<UserDto>(user));

            return RedirectToAction("List");
        }

        [HttpPost]
        public RedirectToRouteResult Delete(int id)
        {
            UserService.DeleteUser(id);

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult AddNew(UserViewModel user)
        {
            try
            {
                UserService.AddNew(Mapper.Map<UserDto>(user));

                return RedirectToAction("List");
            }
            catch (DuplicateUserException exception)
            {
                return Add(new[] { exception.Message });
            }
        }
    }
}

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>

<div class="container-fluid full-width full-height">
    <div class="row header">
        @if (User.Identity.IsAuthenticated)
        {
            Html.RenderPartial("_header");
        }
    </div>
    <div class="row content">
        <div class="container-fluid full-height">
            <div class="panel panel-default full-height body-panel">
                <div class="panel-heading body-title color-main">
                    <div class="row">
                        <div class="col-lg-12 text-center">@ViewBag.Title</div>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="col-lg-2 text-right container-admin-tools">@RenderSection("AdminTools", false)</div>
                        }
                    </div>
                </div>
                <div class="panel-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/main")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

</body>
</html>

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_chart.cshtml
@model TestCaseStorage.Models.Chart.ChartModel

<div class="chart-container">
    <canvas id="@Model.Guid"></canvas>
</div>

<script>
    var ctx = document.getElementById("@Model.Guid");
    var myChart = new Chart(ctx, {
        type: '@Model.Type.ToString().ToLower()',
        data: {
            labels: [@Html.Raw(Model.Labels)],
            datasets: [{
                label: '@Model.YLabel',
                data: [@Model.Values],
                backgroundColor: '@Model.ChartColor.ToLower()',
                borderColor: 'grey',
                borderWidth: 2
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                        callback: function (value) { if (value % 1 === 0) { return value; } }
                    }
                }]
            }
        }
    });
</script>

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_editDeleteSection.cshtml
@model TestCaseStorage.Models.Shared.EditDeleteSectionModel

<div class="col-lg-6 text-right" style="min-width: 40px;">
    @using (Html.BeginForm(Model.EditAction, Model.Controller, FormMethod.Get))
    {
        @Html.Hidden("id", Model.HiddenIdentifier)

        <input class="btn btn-default btn-md button-edit" type="submit" value="Редактировать" />
    }
</div>
<div class="col-lg-6 text-left" style="min-width: 40px;">
    @using (Html.BeginForm(Model.DeleteAction, Model.Controller, FormMethod.Post))
    {
        @Html.Hidden("id", Model.HiddenIdentifier)

        <input class="btn btn-default btn-md button-delete" type="submit" value="Удалить" data-delete-item-name="@Model.DeleteItemName" />
    }
</div>

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_editLine.cshtml
@model TestCaseStorage.Models.Shared.EditLineModel

<div class="row">
    <div class="col-lg-4 col-lg-offset-4 input-group-lg">
        @Html.TextBox(Model.ControlName, Model.ControlValue, new { @class = "form-control navbar-btn", placeholder = Model.PlaceHolder })
    </div>
</div>

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_editorCell.cshtml
@model MvcHtmlString 

<div class="col-lg-3 input-group-lg">
    @Model
</div>

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_editorRow.cshtml
@* first parameter - row label, second parameter - editor cell html *@
@model Tuple<string, MvcHtmlString> 

<div class="row">
    @Html.Partial("_labelCell", Model.Item1)
    @Html.Partial("_editorCell", Model.Item2)
</div>

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_header.cshtml
@{
    Layout = null;
}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="row navigation-row">
            <div class="col-lg-10 no-padding text-left">
                @{ Html.RenderAction("Show", "NavigationMenu"); }
            </div>
            <div class="col-lg-2 text-right">
                <input class="btn btn-default navbar-btn btn-lg" type="button" value="Выйти" onclick="location.href='@Url.Action("Logout", "Login")'" />
            </div>
        </div>
    </div>
</nav>

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_labelCell.cshtml
@model string

<div class="col-lg-2 col-lg-offset-3 text-right">
    @Html.Label(Model, new { @class = "edit-line-label" })
</div>

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_navigationMenu.cshtml
@{
    Layout = null;
}

<div class="col-lg-1 home-btn-container">
    @Html.ActionLink("Домой", "Index", "Home", null, new {@class = "btn btn-default btn-lg navbar-btn home-button", title = "Главная"})
</div>
<div class="col-lg-offset-1 col-lg-3 action-btn-container">
    @Html.ActionLink("Задачи/Ошибки", "List", "Backlog", null, new { @class = "btn btn-default btn-lg navbar-btn" })
</div>
<div class="col-lg-3 action-btn-container">
    @Html.ActionLink("Тест Кейсы", "List", "TestCase", null, new { @class = "btn btn-default btn-lg navbar-btn" })
</div>
<div class="col-lg-3 action-btn-container">
    @Html.ActionLink("Пользователи", "List", "User", null, new { @class = "btn btn-default btn-lg navbar-btn" })
</div>

TestCaseTrackingSystem/TestCaseTrackingSystem/Views/Shared/_noItemsMessage.cshtml
@model string

<div class="row color-main no-items-message text-center">
    @Model
</div>